version: '3'

services:
  backend:
    build:
      context: ./backend
    image: paraspachpute/backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    image: paraspachpute/frontend:latest
    ports:
      - "80:80"  # Expose Nginx port
    depends_on:
      - backend
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: channel_chat
      POSTGRES_USER: channel_chat
      POSTGRES_PASSWORD: password123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# No need for a separate Nginx service, as it's included in the frontend service
